### ISSUE TITLE
The link of pretrained encoder and dataset all not exist

### ISSUE THREAD

**Issue by jojowick22** [1ho0jin1/OSFI-by-FineTuning#2]

**Comment by 1ho0jin1** [comment]
Hi!
Thank you for your interest on our work.
I updated all the links.
I will close this issue.
Feel free to open again if there is any problem.

**Comment by fmac2000** [comment]
Hi - having an issue with the weights also, could you please check the links again?

**Comment by 1ho0jin1** [comment]
Hi, I updated the links. Please give it a check :)
